Moved the 2>&1 redirection after the stdout redirection and added an error message if an error is encoutered.

diff --git a/LibTkGL/makeit b/LibTkGL/makeit
--- a/LibTkGL/makeit
+++ b/LibTkGL/makeit
@@ -137,10 +137,9 @@ if [[ $EXT -eq 1 ]]; then
    #----- The library we don't compile doesn't need to be copied, so link them to the original dir
 
    if [[ $LIB_PATH_OPS != $LIB_PATH ]]; then
-   
       for l in $SLINK_LIBS; do
          if [[ -e $LIB_PATH_OPS/$l ]]; then
-            echo "Copying precompiled $LIB_PATH/$l"
+            echo "Copying precompiled $LIB_PATH_OPS/$l -> $LIB_PATH"
             cp -frd $LIB_PATH_OPS/$l/lib/*.so* $LIB_PATH/lib
             if [[ -e $LIB_PATH_OPS/$l/include ]]; then
                cp -frd $LIB_PATH_OPS/$l/include/* $LIB_PATH/include
@@ -169,7 +168,7 @@ if [[ $EXT -eq 1 ]]; then
       cp -r -p ${ARCH_PATH}/${MESA}/ ${TMP_PATH}/
       (./configure --prefix=${LIB_PATH}/GL --disable-gallium --with-x --with-driver=xlib --disable-driglx-direct
       make
-      make install) 2>&1 > ${TMP_PATH}/${MESA}/build.log
+      make install) > ${TMP_PATH}/${MESA}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
    fi
    #----- Tcl Specifics
 
@@ -178,7 +177,7 @@ if [[ $EXT -eq 1 ]]; then
    mkdir ${TMP_PATH}/tcl${TCL_VERSION}
    cd ${TMP_PATH}/tcl${TCL_VERSION}
    (${ARCH_PATH}/tcl${TCL_VERSION}/unix/configure --prefix=${LIB_PATH}/TCL --enable-threads  --enable-64bit=${x64}
-   make install) 2>&1 > ${TMP_PATH}/tcl${TCL_VERSION}/build.log
+   make install) > ${TMP_PATH}/tcl${TCL_VERSION}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
 
    #----- Tk
    echo "Building ${TMP_PATH}/tk${TCL_VERSION}/build.log"
@@ -189,11 +188,11 @@ if [[ $EXT -eq 1 ]]; then
    #----- Remove visibility-hidden flag from makefile for glCanvas to work
    mv Makefile Makefile.hidden
    sed 's/-DMODULE_SCOPE=\(\\ \|[^ ]\)*[^\\] //' <Makefile.hidden >Makefile
-   make install) 2>&1 > ${TMP_PATH}/tk${TCL_VERSION}/build.log
+   make install) > ${TMP_PATH}/tk${TCL_VERSION}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
 
    #----- Tcllib
    cd ${ARCH_PATH}/Tcllib-${TCLLIB}
-   ./installer.tcl -no-gui -no-nroff -no-examples -no-apps -no-wait -pkg-path ${LIB_PATH}/TCL/lib/tcllib${TCLLIB}
+   ./installer.tcl -no-gui -no-nroff -no-examples -no-apps -no-wait -pkg-path ${LIB_PATH}/TCL/lib/tcllib${TCLLIB} || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
 
    #----- TkImg
    if [[ $ARCH != "AIX" ]]; then
@@ -203,7 +202,7 @@ if [[ $EXT -eq 1 ]]; then
       (${ARCH_PATH}/${TKIMG}/configure --prefix=${LIB_PATH}/TCL --enable-threads --enable-64bit=${x64} --with-tcl=${LIB_PATH}/TCL/lib --with-tk=${LIB_PATH}/TCL/lib
       #----- TCLLIBPATH is necessary to make sure tcl script /usr/bin/dtplite executes on a tclsh with a valid doctools package
       TCLLIBPATH="${LIB_PATH}/TCL/lib $TCLLIBPATH"
-      make install) 2>&1 > ${TMP_PATH}/${TKIMG}/build.log
+      make install) > ${TMP_PATH}/${TKIMG}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
    fi
 
    #----- TkTable
@@ -211,21 +210,21 @@ if [[ $EXT -eq 1 ]]; then
    mkdir ${TMP_PATH}/${TKTABLE}
    cd ${TMP_PATH}/${TKTABLE}
    (${ARCH_PATH}/${TKTABLE}/configure --prefix=${LIB_PATH}/TCL --enable-threads --enable-64bit=${x64} --with-tcl=${LIB_PATH}/TCL/lib
-   make install) 2>&1 > ${TMP_PATH}/${TKTABLE}/build.log
+   make install) > ${TMP_PATH}/${TKTABLE}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
 
    #----- Tkdnd
    echo "Building ${TMP_PATH}/${TKDND}/build.log"
    mkdir ${TMP_PATH}/${TKDND}
    cd ${TMP_PATH}/${TKDND}
    (${ARCH_PATH}/${TKDND}/configure --prefix=${LIB_PATH}/TCL --enable-threads --enable-64bit=${x64} --with-tcl=${LIB_PATH}/TCL/lib
-   make install) 2>&1 > ${TMP_PATH}/${TKDND}/build.log
+   make install) > ${TMP_PATH}/${TKDND}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
 
    #----- libxml2
    echo "Building ${TMP_PATH}/${XML}/build.log"
    mkdir ${TMP_PATH}/${XML}
    cd ${TMP_PATH}/${XML}
    (${ARCH_PATH}/${XML}/configure --prefix=${LIB_PATH} --enable-64bit=${x64} --without-python --enable-shared=yes --enable-static=no
-   make install) 2>&1 > ${TMP_PATH}/${XML}/build.log
+   make install) > ${TMP_PATH}/${XML}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
 
    #----- tDOM
    if [[ $ARCH != "AIX" ]]; then
@@ -233,7 +232,7 @@ if [[ $EXT -eq 1 ]]; then
       mkdir ${TMP_PATH}/${TDOM}
       cd ${TMP_PATH}/${TDOM}
       (${ARCH_PATH}/${TDOM}/configure --prefix=${LIB_PATH}/TCL --enable-threads --enable-64bit=${x64} --with-tclinclude=${LIB_PATH}/TCL/include --with-tcl=${LIB_PATH}/TCL/lib
-      make install) 2>&1 > ${TMP_PATH}/${TDOM}/build.log
+      make install) > ${TMP_PATH}/${TDOM}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
    fi
 
    #----- GDAL Specifics
@@ -243,14 +242,14 @@ if [[ $EXT -eq 1 ]]; then
    mkdir ${TMP_PATH}/${EXPAT}
    cd ${TMP_PATH}/${EXPAT}
    (${ARCH_PATH}/${EXPAT}/configure --prefix=${LIB_PATH} --enable-shared=yes --enable-static=no
-   make install) 2>&1 > ${TMP_PATH}/${EXPAT}/build.log
+   make install) > ${TMP_PATH}/${EXPAT}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
 
    #----- curl
    echo "Building ${TMP_PATH}/${CURL}/build.log"
    mkdir ${TMP_PATH}/${CURL}
    cd ${TMP_PATH}/${CURL}
    (${ARCH_PATH}/${CURL}/configure --prefix=${LIB_PATH} --enable-shared=yes --enable-static=no --without-libssh2 --without-ssl
-   make install) 2>&1 > ${TMP_PATH}/${CURL}/build.log
+   make install) > ${TMP_PATH}/${CURL}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
 
    #----- sqlite
    if [[ $ARCH != "AIX" ]]; then
@@ -258,7 +257,7 @@ if [[ $EXT -eq 1 ]]; then
       mkdir ${TMP_PATH}/${SQLITE}.1
       cd ${TMP_PATH}/${SQLITE}.1
       (${ARCH_PATH}/${SQLITE}.1/configure --prefix=${LIB_PATH} --enable-shared=yes --enable-static=no --enable-threadsafe
-      make install) 2>&1 > ${TMP_PATH}/${SQLITE}.1/build.log
+      make install) > ${TMP_PATH}/${SQLITE}.1/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
    fi
 
    #----- geos
@@ -267,7 +266,7 @@ if [[ $EXT -eq 1 ]]; then
       mkdir ${TMP_PATH}/${GEOS}
       cd ${TMP_PATH}/${GEOS}
       (${ARCH_PATH}/${GEOS}/configure --prefix=${LIB_PATH} --enable-shared=yes --enable-static=no --enable-python=no --enable-ruby=no --with-gnu-ld=yes
-      make install) 2>&1 > ${TMP_PATH}/${GEOS}/build.log
+      make install) > ${TMP_PATH}/${GEOS}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
    fi
 
    #----- jasper
@@ -275,42 +274,42 @@ if [[ $EXT -eq 1 ]]; then
    mkdir ${TMP_PATH}/${JASPER}
    cd ${TMP_PATH}/${JASPER}
    (CFLAGS="-I${TMP_PATH}/${JASPER}/src/libjasper/include $CFLAGS" ${ARCH_PATH}/${JASPER}/configure --prefix=${LIB_PATH} --enable-shared=yes --enable-static=no
-   make install) 2>&1 > ${TMP_PATH}/${JASPER}/build.log
+   make install) > ${TMP_PATH}/${JASPER}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
 
    #----- JPEG
    echo "Building ${TMP_PATH}/${JPEG}/build.log"
    mkdir ${TMP_PATH}/${JPEG}
    cd ${TMP_PATH}/${JPEG}
    (${ARCH_PATH}/${JPEG}/configure --prefix=${LIB_PATH} --enable-shared=yes --enable-static=no 
-   make install) 2>&1 > ${TMP_PATH}/${JPEG}/build.log
+   make install) > ${TMP_PATH}/${JPEG}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
 
    #----- HDF-4
    echo "Building ${TMP_PATH}/${HDF4}/build.log"
    mkdir ${TMP_PATH}/${HDF4}
    cd ${TMP_PATH}/${HDF4}
    (${ARCH_PATH}/${HDF4}/configure --prefix=${LIB_PATH} --enable-shared=yes --enable-static=no --disable-netcdf --disable-fortran --with-jpeg=${LIB_PATH}
-   make install) 2>&1 > ${TMP_PATH}/${HDF4}/build.log
+   make install) > ${TMP_PATH}/${HDF4}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
 
    #----- SZIP
    echo "Building ${TMP_PATH}/${SZIP}/build.log"
    mkdir ${TMP_PATH}/${SZIP}
    cd ${TMP_PATH}/${SZIP}
    (${ARCH_PATH}/${SZIP}/configure --prefix=${LIB_PATH} --enable-shared=yes --enable-static=no
-   make install) 2>&1 > ${TMP_PATH}/${SZIP}/build.log
+   make install) > ${TMP_PATH}/${SZIP}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
 
    #----- HDF-5
    echo "Building ${TMP_PATH}/${HDF5}/build.log"
    mkdir ${TMP_PATH}/${HDF5}
    cd ${TMP_PATH}/${HDF5}
    (${ARCH_PATH}/${HDF5}/configure --prefix=${LIB_PATH} --enable-shared=yes --enable-static=no --with-szlib=${LIB_PATH} --disable-fortran
-   make install) 2>&1 > ${TMP_PATH}/${HDF5}/build.log
+   make install) > ${TMP_PATH}/${HDF5}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
 
    #----- netCDF (Man path on AIX)
    echo "Building ${TMP_PATH}/${NETCDF}/build.log"
    mkdir ${TMP_PATH}/${NETCDF}
    cd ${TMP_PATH}/${NETCDF}
    (${ARCH_PATH}/${NETCDF}/configure --prefix=${LIB_PATH} --disable-netcdf-4 --enable-shared=yes --enable-static=no --enable-c-only --with-hdf5=${LIB_PATH} -with-hdf4=${LIB_PATH}
-   make install) 2>&1 > ${TMP_PATH}/${NETCDF}/build.log
+   make install) > ${TMP_PATH}/${NETCDF}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
 
    #----- grib
    if [[ $ARCH != "AIX" ]]; then
@@ -328,7 +327,7 @@ if [[ $EXT -eq 1 ]]; then
       cp -p ${ARCH_PATH}/${GRIB}/fortran/create_grib_f90.sh ${TMP_PATH}/${GRIB}/fortran/
       cp -p ${ARCH_PATH}/${GRIB}/fortran/grib_f90_*.f90 ${TMP_PATH}/${GRIB}/fortran/
 
-      make install) 2>&1 > ${TMP_PATH}/${GRIB}/build.log
+      make install) > ${TMP_PATH}/${GRIB}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
    fi
 
    #----- ECBUFR
@@ -339,7 +338,7 @@ if [[ $EXT -eq 1 ]]; then
       (${ARCH_PATH}/${ECBUFR}/configure --prefix=${LIB_PATH} --enable-shared=yes --enable-static=no CFLAGS="-I${ARCH_PATH}/${ECBUFR}/API/Headers $CFLAGS"
       #----- Because the headers won't be copied by the install directive if we don't do that
       cp ${ARCH_PATH}/${ECBUFR}/API/Headers/*.h ${TMP_PATH}/${ECBUFR}/API/Headers/
-      make install) 2>&1 > ${TMP_PATH}/${ECBUFR}/build.log
+      make install) > ${TMP_PATH}/${ECBUFR}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
 
       #----- Because ecbufr can't help himself and creates the wrong directory tree by adding an intermediary directory 
       mv ${LIB_PATH}/lib/${ECBUFR}/* ${LIB_PATH}/lib/
@@ -351,14 +350,14 @@ if [[ $EXT -eq 1 ]]; then
       mkdir ${TMP_PATH}/${POSTGRESQL}
       cd ${TMP_PATH}/${POSTGRESQL}
       (${ARCH_PATH}/${POSTGRESQL}/configure --prefix=${LIB_PATH} --enable-shared=yes --enable-static=no --disable-rpath --without-readline --enable-thread-safety --with-openssl --with-libxml --with-includes=${LIB_PATH}/include/libxml2
-      make install) 2>&1 > ${TMP_PATH}/${POSTGRESQL}/build.log
+      make install) > ${TMP_PATH}/${POSTGRESQL}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
 
       #----- ODBC
       echo "Building ${TMP_PATH}/${ODBC}/build.log"
       mkdir ${TMP_PATH}/${ODBC}
       cd ${TMP_PATH}/${ODBC}
       (${ARCH_PATH}/${ODBC}/configure --prefix=${LIB_PATH} --enable-shared=yes --enable-static=no 
-      make install) 2>&1 > ${TMP_PATH}/${ODBC}/build.log
+      make install) > ${TMP_PATH}/${ODBC}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
    fi
 
    #----- PROJ 4
@@ -366,7 +365,7 @@ if [[ $EXT -eq 1 ]]; then
    mkdir ${TMP_PATH}/${PROJ}
    cd ${TMP_PATH}/${PROJ}
    (${ARCH_PATH}/${PROJ}/configure --prefix=${LIB_PATH} --enable-shared=yes --enable-static=no
-   make install) 2>&1 > ${TMP_PATH}/${PROJ}/build.log
+   make install) > ${TMP_PATH}/${PROJ}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
 
    #----- gdal (Don't forget to add stdio.h to frmts/msg/msgcommand.h)
    #----- On AIX, have to wrap the int64 definition betweer ifndef _AIX in frmts/gtiff/libtiff/tiff.h, frmts/fit/gstTypes.h, ogr/ogrsf_frmts/shape/shpopen.c
@@ -393,7 +392,7 @@ if [[ $EXT -eq 1 ]]; then
       --with-xml2=${LIB_PATH}/bin/xml2-config \
       --with-hdf4=${LIB_PATH} \
       --with-netcdf=${LIB_PATH}
-      make install) 2>&1 > ${TMP_PATH}/${GDAL}/build.log
+      make install) > ${TMP_PATH}/${GDAL}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
    else
       (./configure --prefix=${LIB_PATH} --with-threads=yes --disable-rpath --enable-shared=yes --enable-static=no \
       --with-libz=internal \
@@ -419,7 +418,7 @@ if [[ $EXT -eq 1 ]]; then
       --with-odbc=${LIB_PATH} \
       --with-netcdf=${LIB_PATH} \
       --with-fgdb=${LIB_PATH}
-      make install) 2>&1 > ${TMP_PATH}/${GDAL}/build.log
+      make install) > ${TMP_PATH}/${GDAL}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
    fi
    
    rm -f -r ${TMP_PATH}
