Update to makeit script for various platforms.

diff --git a/LibTkGL/makeit b/LibTkGL/makeit
--- a/LibTkGL/makeit
+++ b/LibTkGL/makeit
@@ -66,20 +66,19 @@ PROC=`uname -m | tr _ -`
 SRC_PATH=`pwd`
 TMP_PATH=${SSM_DEV}/build/${ORDENV_PLAT}                                  #----- Temporary directory where the external libraries will be compiled
 LIB_PATH=${SSM_DEV}/workspace/${SSM_NAME}                                 #----- Where to install libraries
-LIB_EER=${SSM_DEV}/workspace/eerUtils_3.2.0${COMP}_${ORDENV_PLAT}         #----- Location of eer library
+LIB_EER=${SSM_DEV}/workspace/eerUtils_3.1.3${COMP}_${ORDENV_PLAT}         #----- Location of eer library
+EXT_LIB_PATH=${EXT_LIB_PATH}/${ORDENV_PLAT}
 
 export LD_LIBRARY_PATH=${LIB_PATH}/lib:$LD_LIBRARY_PATH
 export LIBRARY_PATH=${LIB_PATH}/lib:$LIBRARY_PATH
 
 if [[ $PROC == "x86_64" ]]; then
    x64=yes
-   export CFLAGS=-m64
-   export CXXFLAGS=-m64
 else
    x64=no
 fi
 
-if [[ -n $INTELCOMP_HOME ]]; then
+if [[ -n $INTEL_LICENSE_FILE ]]; then
    export CC=icc
    export CXX=icpc
 fi
@@ -137,7 +136,7 @@ if [[ $EXT -eq 1 ]]; then
 
    #----- not recompiled yet
    KKDU=kakadu-6.3
-   RMN=librmn-15.2
+   RMN=librmn-16.0
 
    #----- Define the list of items we won't compile but will link with
    if [[ $ARCH != "AIX" ]]; then
@@ -233,17 +232,17 @@ if [[ $EXT -eq 1 ]]; then
    ./installer.tcl -no-gui -no-nroff -no-examples -no-apps -no-wait -pkg-path ${LIB_PATH}/TCL/lib/tcllib${TCLLIB} || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
 
    #----- TkImg
-   if [[ $ARCH != "AIX" ]]; then
-      echo "Building ${TMP_PATH}/${TKIMG}/build.log"
-      mkdir ${TMP_PATH}/${TKIMG}
-      cd ${TMP_PATH}/${TKIMG}
-      
-      #----- Because some setup enable jbig without the big stuff
-      (${EXT_SRC_PATH}/${TKIMG}/configure --prefix=${LIB_PATH}/TCL --enable-threads --enable-64bit=${x64} --with-tcl=${LIB_PATH}/TCL/lib --with-tk=${LIB_PATH}/TCL/lib
-      #----- TCLLIBPATH is necessary to make sure tcl script /usr/bin/dtplite executes on a tclsh with a valid doctools package
-      TCLLIBPATH="${LIB_PATH}/TCL/lib $TCLLIBPATH"
-      make install) > ${TMP_PATH}/${TKIMG}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
-   fi
+#    if [[ $ARCH != "AIX" ]]; then
+#       echo "Building ${TMP_PATH}/${TKIMG}/build.log"
+#       mkdir ${TMP_PATH}/${TKIMG}
+#       cd ${TMP_PATH}/${TKIMG}
+#       
+#       #----- Because some setup enable jbig without the big stuff
+#       (${EXT_SRC_PATH}/${TKIMG}/configure --prefix=${LIB_PATH}/TCL --enable-threads --enable-64bit=${x64} --with-tcl=${LIB_PATH}/TCL/lib --with-tk=${LIB_PATH}/TCL/lib
+#       #----- TCLLIBPATH is necessary to make sure tcl script /usr/bin/dtplite executes on a tclsh with a valid doctools package
+#       TCLLIBPATH="${LIB_PATH}/TCL/lib $TCLLIBPATH"
+#       make install) > ${TMP_PATH}/${TKIMG}/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
+#    fi
 
    #----- TkTable
    echo "Building ${TMP_PATH}/${TKTABLE}/build.log"
@@ -304,13 +303,13 @@ if [[ $EXT -eq 1 ]]; then
    fi
 
    #----- sqlite
-#   if [[ $ARCH != "AIX" ]]; then
-#      echo "Building ${TMP_PATH}/${SQLITE}.1/build.log"
-#      mkdir ${TMP_PATH}/${SQLITE}.1
-#      cd ${TMP_PATH}/${SQLITE}.1
-#      (${EXT_SRC_PATH}/${SQLITE}.1/configure --prefix=${LIB_PATH} --enable-shared=yes --enable-static=no --enable-threadsafe
-#      make install) > ${TMP_PATH}/${SQLITE}.1/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
-#   fi
+   if [[ $ARCH != "AIX" ]]; then
+      echo "Building ${TMP_PATH}/${SQLITE}.1/build.log"
+      mkdir ${TMP_PATH}/${SQLITE}.1
+      cd ${TMP_PATH}/${SQLITE}.1
+      (${EXT_SRC_PATH}/${SQLITE}.1/configure --prefix=${LIB_PATH} --enable-shared=yes --enable-static=no --enable-threadsafe
+      make install) > ${TMP_PATH}/${SQLITE}.1/build.log 2>&1 || { err=$?; printf "\n*** ERROR *** : An error occurred (code $err). Check log for details.\n"; exit $err; }
+   fi
 
    #----- geos
    if [[ $ARCH != "AIX" ]]; then
@@ -549,7 +548,7 @@ if [[ $SPI -eq 1 ]]; then
    cd TclSystem
    if [[ $REC -eq 1 ]]; then
       make distclean
-      autoconf2.50
+      autoconf
       ./configure \
       --prefix=${LIB_PATH}/TCL \
       --exec-prefix=${LIB_PATH}/TCL \
@@ -565,7 +564,7 @@ if [[ $SPI -eq 1 ]]; then
    cd ../TkglCanvas
    if [[ $REC -eq 1 ]]; then
       make distclean
-      autoconf2.50
+      autoconf
       ./configure \
       --prefix=${LIB_PATH}/TCL/ \
       --exec-prefix=${LIB_PATH}/TCL/ \
@@ -581,7 +580,7 @@ if [[ $SPI -eq 1 ]]; then
    cd ../TclGeoEER
    if [[ $REC -eq 1 ]]; then
          make distclean
-         autoconf2.50
+         autoconf
          ./configure \
       --prefix=${LIB_PATH}/TCL/ \
       --exec-prefix=${LIB_PATH}/TCL \
@@ -605,7 +604,7 @@ if [[ $SPI -eq 1 ]]; then
    cd ../TclR
    if [[ $REC -eq 1 ]]; then
          make distclean
-         autoconf2.50
+         autoconf
          ./configure \
       --prefix=${LIB_PATH}/TCL/ \
       --exec-prefix=${LIB_PATH}/TCL \
